version: 2
updates:

- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/Dublin
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: faker
    versions:
    - 5.0.0
    - 7.0.1

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Europe/Dublin
    open-pull-requests-limit: 10
    target-branch: develop
