repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 0710b94280408eef12748cde4782972942370ad2  # frozen: v0.8.0
    hooks:
      - id: ruff
