# -*- coding: utf-8 -*-

"""
List of common ESSIDs.
"""

# Based on https://wigle.net/stats#ssidstats.
COMMON_ESSIDS = (
    '3Com',
    'Airport_Free_WiFi_AENA',
    'AndroidAP',
    'AndroidTether',
    'eduroam',
    'Exhibitor Internet',
    'FBI Surveillance Van',
    'freeBestBuywifi',
    'freebox',
    'Free Internet Access',
    'Free Public WiFi',
    'FRITZ!Box',
    'FRITZ!Box Fon WLAN',
    'FRITZ!Box Guest Access',
    'GetYourOwn',
    'get your own WiFi',
    'GuestAccess',
    'Guest Network',
    'GuestWiFi',
    'GuestWireless',
    'H&M Free WiFi',
    'Home Network',
    'Home Sweet Home',
    'Horizon Wi-Free',
    'KFC Free WiFi',
    'McDonalds Free WiFi',
    'MGMResorts-WiFi',
    'Moscow_WiFi_FREE',
    'NETGEAR-5G-GUEST',
    'Neuf WiFi',
    'Nordstrom_Wi-Fi',
    'Radisson_Guest',
    'Rostelecom',
    'SFR WiFi Public',
    'Starbucks WiFi',
    'Swisscom_Auto_Login',
    'visitors',
    'Vodafone Homespot',
    'Vodafone Hotspot',
    'Vodafone-Guest',
    'Welcome',
)
